Tests are written
VK-BMSTU-QA/units-automn-2022 pull request #1
Opened 2022-10-13 16:51 UTC by kirill555101

2022-10-16 14:33 UTC, Victorius19 approved these changes

2022-10-16 14:33 UTC, Victorius19 commented on src/Order/Order.test.tsx
> +		const orderWithEmptyItems: Order = {};
Можно же не присваивать им сразу объект?

2022-10-16 18:27 UTC, kirill555101 commented on src/Order/Order.test.tsx
> +		const orderWithEmptyItems: Order = {};
Можно и так

2022-10-18 17:49 UTC, alexey-ershkov requested changes
Привет) отписал комментов

2022-10-18 17:49 UTC, alexey-ershkov commented on src/Order/Order.test.tsx
> +			expect(getDate).toHaveBeenCalledTimes(1);
Можно еще проверить данные, с которыми вызывалась функция

2022-10-18 17:49 UTC, alexey-ershkov commented on src/utils/sortOrders.test.ts
> +	describe('when sortType is not valid', () => {
Кажется тут вложенный describe можно опустить

2022-10-18 17:49 UTC, alexey-ershkov commented on src/utils/sortOrders.test.ts
> +type testTable = {
Лайк за тайпинг

2022-11-01 16:44 UTC, closed without merging