add tests
VK-BMSTU-QA/units-automn-2022 pull request #9
Opened 2022-10-13 17:21 UTC by Kostich31

2022-10-13 17:41 UTC, Kislv commented
аппрув

2022-10-16 11:49 UTC, alexey-ershkov requested changes
Привет, накинул комментов

2022-10-16 11:49 UTC, alexey-ershkov commented on src/Order/Order.test.tsx
> +		(getDate as jest.Mock).mockReturnValue('13 октября, чт, 2022 год');
Это значение где-то используется?

2022-10-16 11:49 UTC, alexey-ershkov commented on src/Order/Order.test.tsx
> +		expect(wrapper).toMatchSnapshot();
По-хорошему нужно проверять еще была ли вызвана getDate и с каким значением. Иначе мок бессмысленен

2022-10-16 11:49 UTC, alexey-ershkov commented on src/Order/Order.test.tsx
> +		const order = fakeOrders[1];
Лучше не использовать fakeOrders, так как этот массив может измениться и тесты попадают

2022-10-16 11:49 UTC, alexey-ershkov commented on src/utils/sortOrders.test.ts
> +});
Нет тестов на sortOrders, надо добавить

2022-10-16 11:49 UTC, alexey-ershkov commented on src/utils/sortOrders.test.ts
> +	const dateNow = Date.now();
при каждом прогоне теста будет разное, по сути можно просто числа передавать в date, этого хватит для проверки

2022-10-16 11:49 UTC, alexey-ershkov commented on src/Order/Order.test.tsx
> +	it('Test null order', () => {
Давай придерживаться конвенции it ('should ...')

2022-10-18 17:07 UTC, alexey-ershkov requested changes
Накинул еще комментов

2022-10-18 17:07 UTC, alexey-ershkov commented on src/Order/Order.test.tsx
> +		(getDate as jest.Mock);
а нужен ли этот код?

2022-10-18 17:07 UTC, alexey-ershkov commented on src/utils/sortOrders.test.ts
> +		expect(sortOrders(orders!, sortFunction)).toBe(expected);
sortOrders всегда возвращает undefined, нужно проверять что вызывалась или не вызывалась sortFunction

2022-10-19 21:59 UTC, Kostich31 commented on src/Order/Order.test.tsx
> +		(getDate as jest.Mock);
В целом в данном случае не нужен, без него тесты не упадут. В тех местах, где проверяется вызов getDate все будет работать правильно. Я так понимаю, это из-за того, что сама функция getDate работает правильно.

2022-10-20 07:33 UTC, alexey-ershkov requested changes

2022-10-20 07:33 UTC, alexey-ershkov commented on src/Order/Order.test.tsx
> +		(getDate as jest.Mock);
Не совсем так, когда пишешь `jest.mock('../utils/getDate');`, то у тебя реальная функция getDate подменяется на jest.fn(), на которой ты можешь отслеживать события и которая имеет пустую реализацию. Как ты можешь заметить в обновлениях снепшотов, единственное, что изменилось, что вместо даты указанной в mockReturnValue у тебя не том же месте пустое значение

ну и beforeEach тебе уже не нужен, так как оно ничего не делает

2022-10-20 08:19 UTC, Kostich31 commented on src/Order/Order.test.tsx
> +		(getDate as jest.Mock);
Я убрал в таком случае beforeEach, т.к. без mockReturnValue эта строчка вообще не имеет смысла.

2022-10-20 08:32 UTC, alexey-ershkov approved these changes

2023-01-28 12:30 UTC, closed without merging